# inspired by exoplanet: https://github.com/exoplanet-dev/exoplanet/blob/master/.pre-commit-config.yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace

  - id: end-of-file-fixer

  - id: debug-statements

- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.2
  hooks:
  - id: seed-isort-config
    args: [--application-directories=src]

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.20
  hooks:
  - id: isort
    args: [-rc src]
    additional_dependencies: [toml]

- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
  - id: black
