coverage:
  precision: 2
  round: nearest
  range: "40...90"
  ignore:
    - "src/simmer/tests"
    - "src/simmer/aodirs.py"
    - "src/simmer/__init__.py"
    - "__init__.py"
codecov:
  disable_default_path_fixes: true
