version: 1
update_configs:
  # Keep setup.py secure and up-to-date,
  # batching pull requests daily
  - package_manager: "python"
    directory: "/"
    update_schedule: "daily"
    allow:
      # Allow only direct updates for
      # pandas and any packages starting "pandas"
      - dependency-name: "pandas*"
        dependency-type: "direct"
      # Allow only direct updates for
      # pandas and any packages starting "pandas"
      - dependency-name: "numpy*"
        dependency-type: "direct"
      # Allow only direct updates for
      # pandas and any packages starting "pandas"
      - dependency-name: "photutils*"
        dependency-type: "direct"
