# inspired by exoplanet-dev/exoplanet: https://github.com/exoplanet-dev/exoplanet/blob/master/.github/workflows/style.yml
name: Style

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U black isort black_nbconvert
      - name: Check the style
        run: |
          isort -c -rc src
          black --check src
          black_nbconvert --check .
